Study/seoyeongkim/1
techeer-sv/Do-It-Algorithm-Study pull request #8
Opened 2023-04-19 17:06 UTC by ksy990628

## 💡 PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our <a href="https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit">guidelines</a>
- [ ] Reviewers
- [ ] Assignees
- [ ] Link Issue number

---

## 💡 PR Type
What kind of change does this PR introduce?

- [ ] Upload a solved problem
- [ ] Upload a blog

<br>

---

## ✏︎ What is the new behavior?

Issue Number: Closes #5

Context
(공통) 카카오 : 순위 검색

2023-04-20 12:38 UTC, yunhobb commented
https://school.programmers.co.kr/questions/16839

댓글에 참고할만한 방향성이 적혀 있어서 궁금하실까봐 남겨드립니다!

2023-04-20 13:33 UTC, ksy990628 commented
분명 이진 탐색, 정렬도 써야하지만, **HashMap을 쓸 줄 아냐가 관건인 것 같은 문제...**
hash는 검색할 때 시간복잡도가 1이다. 해시함수에 값을 넣으면 바로 답이 나와 그걸 찾으면 되기 때문!

2023-04-24 13:31 UTC, yunhobb requested changes

2023-04-24 13:31 UTC, yunhobb commented on seoyeong/code/Week1.java
> +            for (int j=idx; j<info.length; j++){
효율성 관련해서 질문을 찾아보니 O(n^2) 이면 효율성을 통과 못할거 같다고 질문하기에 적혀있네요 !

2023-04-24 13:33 UTC, yunhobb approved these changes

2023-04-24 14:56 UTC, merged